# 예제 03. axis와 브로드캐스팅
빅데이터프로그래밍 · 2주차

## 목표
- `axis` 가 어느 방향인지 이해한다
- 행별·열별 통계를 구한다
- 모양이 다른 배열끼리 계산되는 규칙을 확인한다


In [ ]:
import numpy as np

scores = np.array([[88, 92, 79],
                   [95, 61, 84],
                   [70, 100, 66],
                   [82, 74, 91]])
print(scores.shape)   # (학생 4, 과목 3)


## 1. axis 없는 계산 — 전체를 하나로


In [ ]:
print("전체 평균 :", scores.mean())
print("전체 합계 :", scores.sum())
print("전체 최대 :", scores.max())


## 2. axis=0 은 행을 따라 내려가며 계산 → 과목별
## axis=1 은 열을 따라 옆으로 계산 → 학생별

**축은 "사라지는 방향"입니다.** (4, 3) 배열에서 `axis=0` 으로 평균을 구하면 4가 사라져 (3,) 이 됩니다.


In [ ]:
print("과목별 평균 axis=0 :", scores.mean(axis=0), scores.mean(axis=0).shape)
print("학생별 평균 axis=1 :", scores.mean(axis=1), scores.mean(axis=1).shape)


In [ ]:
print("과목별 최고점 :", scores.max(axis=0))
print("학생별 최고점 :", scores.max(axis=1))
print("학생별 최고 과목 번호 :", scores.argmax(axis=1))


## 3. 최댓값의 위치 찾기
`argmax` 는 한 줄로 펴진 위치를 주므로, `unravel_index` 로 (행, 열) 로 바꿉니다.


In [ ]:
flat = scores.argmax()
pos = np.unravel_index(flat, scores.shape)
print("가장 높은 점수:", scores.max(), "위치:", pos)


## 4. 브로드캐스팅 — 모양이 달라도 계산됩니다


In [ ]:
print(scores + 5)          # 스칼라는 모든 원소에

bonus = np.array([1, 2, 3])           # (3,) — 과목별 가산점
print(scores + bonus)                  # 각 행에 더해집니다
print((scores + bonus).shape)


In [ ]:
# 학생별로 다른 값을 더하려면 열 모양 (4, 1) 로 만들어야 합니다
weight = np.array([1, 2, 3, 4]).reshape(4, 1)
print(scores + weight)


In [ ]:
a = np.array([1, 2, 3])
a + 10
# [11 12 13]

# 스칼라 10은 모양 ()이고, a는 (3,)입니다.

# 스칼라는 모든 차원에서 “길이 1”인 것처럼 취급되어 (3,)로 브로드캐스트됩니다.

In [ ]:
a = np.array([1, 2, 3])        # shape: (3,)
b = np.array([[10, 20, 30]])   # shape: (1, 3)

a + b
# [[11 22 33]]

# 뒤에서부터 비교:

   # 마지막 차원: 3 vs 3 → 같음

   # 그 앞 차원: (없음) vs 1 → 한쪽이 1이므로 OK

In [ ]:
# (3, 1) + (1, 4) → (3, 4)
a = np.arange(3).reshape(3, 1)  # [[0],[1],[2]]
b = np.arange(4).reshape(1, 4)  # [[0,1,2,3]]

a + b
# [[0 1 2 3]
#  [1 2 3 4]
#  [2 3 4 5]]
# shape: (3, 4)

# 차원 비교:

   # 축 1: 1 vs 4 → 한쪽이 1

   # 축 0: 3 vs 1 → 한쪽이 1
   # → 결과 shape는 각 축의 최대값인 (3, 4)가 됩니다.

In [ ]:
#  브로드캐스팅이 실패하는 경우

a = np.zeros((3, 4))
b = np.zeros((2, 4))

a + b
# ValueError: operands could not be broadcast together with shapes (3,4) (2,4)

# 뒤에서부터 비교:

  # 축 1: 4 vs 4 → OK

  # 축 0: 3 vs 2 → 다르고, 어느 쪽도 1이 아니므로 브로드캐스팅 불가

## 5. 표준화 — 통계에서 하던 계산을 한 줄로


In [ ]:
mean = scores.mean(axis=0)     # 과목별 평균
std = scores.std(axis=0)       # 과목별 표준편차

z = (scores - mean) / std
print(np.round(z, 2))
print("표준화 후 과목별 평균:", np.round(z.mean(axis=0), 6))


## 직접 해보기
1. 학생별 합계를 구하세요.
2. 각 과목 점수를 그 과목의 최댓값으로 나눠 0~1로 바꾸세요.


In [ ]:
# 여기에 작성하세요
